# Generated by Django 5.1.7 on 2025-03-18 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcao',
            fields=[
                ('codigo_acao', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_acao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de ação',
                'verbose_name_plural': 'Tipos de ação',
                'db_table': 'tipo_acao',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investimento', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_prevista', models.DateField()),
                ('data_cadastro', models.DateField()),
                ('codigo_acao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.tipoacao')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'db_table': 'acao',
            },
        ),
    ]
