# Generated by Django 5.1.7 on 2025-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoacao',
            name='codigo_acao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
