# Generated by Django 5.1.7 on 2025-03-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_tipoacao_codigo_acao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acao',
            options={'verbose_name': 'ação', 'verbose_name_plural': 'ações'},
        ),
        migrations.AlterModelOptions(
            name='tipoacao',
            options={'verbose_name': 'tipo de ação', 'verbose_name_plural': 'tipos de ação'},
        ),
        migrations.AlterField(
            model_name='acao',
            name='codigo_acao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.tipoacao', verbose_name='ação'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='investimento',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='investimento previsto'),
        ),
    ]
